def right_justify(s):
    print(' ' * 70 + s)


# right_justify('monty')

# 2 not done yet? page 27
def do_twice(print_spam):
    print_spam()
    print_spam()


def print_spam():
    print('spam')


def print_twice(spam):
    print(spam)
    print(spam)


# do_twice(print_spam)

def gridline():
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')

    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+')

    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+')
    # down
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')

    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+')

    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|', end=' ' * 9)
    print('|')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+', end=' ')
    print('- ' * 4, end='')
    print('+')


gridline()
